### ISSUE TITLE
does not answer to http requests on port 8000 when daemonized

### ISSUE THREAD

**Issue by ZaphodB** [ahupowerdns/metronome#10] opened 2014-05-30 13:45 UTC
metronome does not seem to be responding to or even receiving packets on port [::]:8000 when daemonized. 

When started via

$ ./metronome --daemon=0 --stats-directory=./stats
Launched Carbon functionality on [::]:2003
Launched webserver on [::]:8000

it works as advertised.

**Comment by RvdE** [comment] 2015-01-09 21:01
I have the exact same issue on FreeBSD 10.1

**Comment by ahupowerdns** [comment] 2015-01-10 07:52
Zaphod, which OS are you on? When it happens, could you strace the whole thing? I can't reproduce here is the problem. Also, are you doubly sure you are connecting to [::]:8000 and not 127.0.0.1:8000?

**Comment by ahupowerdns** [comment] 2015-01-10 07:53
RvdE: the strace question is for you as well of course ;-)

**Comment by ahupowerdns** [comment] 2015-01-10 07:59
Ok, I can reproduce now. Pls wait.

**Comment by ahupowerdns** [comment] 2015-01-10 12:52
Fixed in a33d01fa8f816cc760414861780291d326c7cf2a - this had to do with forking _after_ creating threads, which appears to work differently on some architectures than others.

**Closed by ahupowerdns** 2015-01-10 12:52 UTC

**Comment by ahupowerdns** [comment] 2015-01-10 15:31
actually fixed one commit later, sorry
