### ISSUE TITLE
ability to use multiple carbon server

### ISSUE THREAD

**Issue by zozo6015** [ahupowerdns/metronome#16] opened 2015-01-17 22:07 UTC
Can we have the option to set up multiple carbon servers in powerdns?

**Comment by Habbie** [comment] 2015-03-03 09:46
duplicate of https://github.com/PowerDNS/pdns/issues/2093

**Comment by pieterlexis** [comment] 2016-09-16 16:09
fixed in powerdns

**Closed by pieterlexis** 2016-09-16 16:09 UTC
